### ISSUE TITLE
ERROR when runing GMVAE_main.py

### ISSUE THREAD

**Issue by MengQiuchen** [psanch21/VAE-GMVAE#5]
When I trained GMVAE with MNIST or FREY dataset:
`python3 GMVAE_main.py --model_type=3 --dataset_name=FREY --sigma=0.001 --z_dim=8 --w_dim=2 --K_clusters=8 --hidden_dim=64 --num_layers=2 --epochs=20 --batch_size=32 --drop_prob=0.3 --l_rate=0.01 --train=0 --results=1 --plot=1 --restore=1 --early_stopping=1`
I met the same error:
`Model does NOT exist
Traceback (most recent call last):
  File "GMVAE_main.py", line 93, in <module>
    x_samples, z_samples, w_samples = vae_model.generate_samples(data_test, num_batches=2)
TypeError: cannot unpack non-iterable NoneType object
`
I would appreciate your help. 

PS: VAE works well.

Version:
- tensorflow: 1.14.0
- matplotlib: 3.1.1
- numpy: 1.17.2

**Comment by psanch21** [comment]
Hi MQCodingFarmer,

First of all, sorry for the delay in the response.  I would say your problem arises because there is some error during the load of the model. As a consequence, line 217 of the screenshot is executed.

<img width="1011" alt="Screenshot 2020-01-11 at 13 32 10" src="https://user-images.githubusercontent.com/16980895/72204331-c7238300-3476-11ea-8921-407cc4a55bba.png">


Hope this helps.
